# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: "ap-northeast-2"
  BUCKET_NAME: "image-uploader-cicd-bucket"
  DEPLOY_GROUP_NAME: "ImageUploaderCICDGroup"
  CODE_DEPLOY_APP_NAME: "ImageUploaderCodeDeploy"
permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Permission Gradlew
      run: chmod +x ./gradlew
      shell: bash
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Make Zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
    - name: Config AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::242842444353:role/GithubActionRole
        aws-region: ${{env.AWS_REGION}}
    - name: Copy Zip File to s3
      run: aws s3 cp ./$GITHUB_SHA.zip s3://${{env.BUCKET_NAME}}/
    - name: Code deploy to EC2 Instance
      run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOY_GROUP_NAME --s3-location bucket=$BUCKET_NAME ,bundleType=zip, key=$GITHUB_SHA.zip
